# Generated by Django 3.2 on 2021-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeNo', models.IntegerField()),
                ('EmployeeName', models.CharField(max_length=20)),
                ('EmployeeAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
